# Generated by Django 4.2.11 on 2024-04-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.TextField(help_text='Enter the FSSAI License Number', max_length=50)),
                ('gstin', models.TextField(blank=True, help_text='Enter the Registered GST Number', max_length=50, null=True)),
                ('location', models.TextField(help_text='Location Or Area Name in Text', max_length=100)),
                ('serving_options', models.TextField(choices=[('SELF-PICKUP', 'SELF SERVICE'), ('ON-TABLE', 'TABLE SERVING'), ('BOTH-OPTIONS', 'BOTH')], max_length=20)),
                ('opening_time', models.TimeField(blank=True, help_text='Time to get Brand | Store Online', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Time to get Brand | Store Offline', null=True)),
                ('cooking_time', models.TextField(blank=True, help_text='Approx Time under which Food will be Prepared (Preparation Time)', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Brands | Shop Name',
            },
        ),
        migrations.CreateModel(
            name='MarketAreaCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Area | Market | Cluster Name/Title ', max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('location', models.TextField(help_text='Location Or Area Name in Text', max_length=100)),
                ('location_co_ordinates', models.TextField(blank=True, help_text='Only Internal Purpose', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Area | Market | Cluster Details/Location',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Category's Name/Title ", max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': "Menu Category's",
            },
        ),
        migrations.CreateModel(
            name='BrandMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.TextField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=50)),
                ('item_available', models.TextField(choices=[('IN-STOCK', 'IN-STOCK'), ('OUT-OF-STOCK', 'OUT-OF-STOCK')], default='IN-STOCK', max_length=20)),
                ('item_selling_price', models.FloatField()),
                ('item_discounted_price', models.FloatField(blank=True, null=True)),
                ('item_promotion_value', models.IntegerField(blank=True, help_text='Ordering of Promotion Item', null=True)),
                ('item_order_limit', models.IntegerField(blank=True, help_text='Max number of Order Place in single Checkout', null=True)),
                ('item_bulk_order', models.TextField(blank=True, choices=[('IN-STOCK', 'IN-STOCK'), ('OUT-OF-STOCK', 'OUT-OF-STOCK')], help_text='Product/Item could be Builk Ordered Or Not', max_length=20, null=True)),
                ('item_bulk_order_limit', models.IntegerField(blank=True, help_text='Lower Limit after which Price is Applicable', null=True)),
                ('item_bulk_order_price', models.IntegerField(blank=True, help_text='Bulk order Discounted Price', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.menucategory')),
            ],
            options={
                'verbose_name': "Brand Menu Item's",
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='market_area_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.marketareacluster'),
        ),
    ]
