# Generated by Django 4.2.11 on 2024-04-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_brand_options_brand_title_brandmenu_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brands | Shop Details', 'verbose_name_plural': 'Brands | Shop Details'},
        ),
        migrations.AlterModelOptions(
            name='brandmenu',
            options={'verbose_name': 'Brand Menu Item', 'verbose_name_plural': "Brand Menu Item's"},
        ),
        migrations.AlterModelOptions(
            name='marketareacluster',
            options={'verbose_name': 'Area | Market | Cluster Details/Location', 'verbose_name_plural': 'Area | Market | Cluster Details/Locations'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': "Menu Category's", 'verbose_name_plural': "Menu Category's"},
        ),
    ]
