# Generated by Django 4.2.11 on 2024-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_brand_options_alter_brandmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cooking_time',
            field=models.CharField(blank=True, help_text='Approx Time under which Food will be Prepared (Preparation Time)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='gstin',
            field=models.CharField(blank=True, help_text='Enter the Registered GST Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='license_number',
            field=models.CharField(help_text='Enter the FSSAI License Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='location',
            field=models.CharField(help_text='Location Or Area Name in Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='serving_options',
            field=models.CharField(choices=[('SELF-PICKUP', 'SELF SERVICE'), ('ON-TABLE', 'TABLE SERVING'), ('BOTH-OPTIONS', 'BOTH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(help_text='Enter Brands | Shop Name ', max_length=200),
        ),
        migrations.AlterField(
            model_name='brandmenu',
            name='item_available',
            field=models.CharField(choices=[('IN-STOCK', 'IN-STOCK'), ('OUT-OF-STOCK', 'OUT-OF-STOCK')], default='IN-STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='brandmenu',
            name='item_bulk_order',
            field=models.CharField(blank=True, choices=[('IN-STOCK', 'IN-STOCK'), ('OUT-OF-STOCK', 'OUT-OF-STOCK')], help_text='Product/Item could be Builk Ordered Or Not', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brandmenu',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brandmenu',
            name='item_type',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marketareacluster',
            name='location',
            field=models.CharField(help_text='Location Or Area Name in Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketareacluster',
            name='location_co_ordinates',
            field=models.CharField(blank=True, help_text='Only Internal Purpose', max_length=100, null=True),
        ),
    ]
